# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cars World' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cars World

  pod 'CountryPickerSwift'
  pod 'DropDown'
  pod 'Cosmos'
  pod 'KMPlaceholderTextView'
  pod 'ImageSlideshow'
  pod 'ImageSlideshow/SDWebImage'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'NVActivityIndicatorView'
  pod 'RangeSeekSlider'
  pod 'DLRadioButton'
  pod 'Toast-Swift'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'GooglePlaces'
  pod 'FlagKit'
  pod 'XLPagerTabStrip'
  pod 'DZNEmptyDataSet'
  pod 'PayPal-iOS-SDK'
  pod 'RangeSeekSlider'
  pod 'SwiftRangeSlider'
  pod 'Socket.IO-Client-Swift'
  pod 'UITextView+Placeholder'
  pod 'DropDown'
  pod "MIBadgeButton-Swift", :git => 'https://github.com/mustafaibrahim989/MIBadgeButton-Swift.git', :branch => 'master'
  pod "MIBadgeButton"

end
